### ISSUE TITLE
Modal protected override void OnInitialized()  inconsistent after showing Modal

### ISSUE THREAD

**Issue by pishah** [vikramlearning/blazorbootstrap#319]
I am trying to create a dynamic modal

Debugger shows this is called every time. And the Modal is shown every time. But the protected override void OnInitialized() is not being called every time, only sometimes. What would cause that? I would expect it to be called every time I use await modal.ShowAsync, is that not right?

The code to show the modal is
await modal.ShowAsync<EditStudent>(title: "Student Details", parameters: parameters);

and in the EditStudent.Razor I have the 
protected override void OnInitialized(){}

But it is only being called on first time. After that the Initialized is never updated. I have checked all the parameters and they are being applied correctly, just the OnInitialized not being called after first use. Any guidance would be appreciated. Not sure if it is a bug or on my end.

**Comment by pishah** [comment]
Seems if I add
private async Task OnModalHidingAsync()
{
    await modal.HideAsync();
}

It fixes the issue and OnInitialized is called every time after closing and opening the Modal. Not sure if that is by design to have to do that, but it works for me.

**Comment by gvreddy04** [comment]
@pishah Can you share the sample code or GitHub repo with minimal steps for better understanding.

**Comment by gvreddy04** [comment]
@pishah Thank you for using BlazorBoostrap. Modal's `OnInitializedAsync `will only be called the first time. If you call ShowAsync(...) a second time, OnInitialized will not be called because it is already initialized. This is Modal's internal implementation. What issue are you facing? You can update the parameters dynamically based on your requirements. If you see any issue with parameter assignment or anything else, please create a separate issue.
