### ISSUE TITLE
Blazorise acknowledgement

### ISSUE THREAD

**Issue by stsrki** [vikramlearning/blazorbootstrap#563]
I'm writing this as an open letter because I don’t see any other way that you @gvreddy04(Vikram), might acknowledge the issue beforehand.

To everyone who will read this thread, I will first write some facts in chronological order:

- Sometimes in July I found about this project BlazorBootstrap and I liked what I saw. It was a cool project. I also noticed that some parts of the code base had copy/pasted code from Blazorise. That was interesting.
- I contacted the author, Vikram, on July 14th 2023., to know him better and learn about his motivations. Even wanted to give him a job offer.
- Few days later, we met over the Zoom call. I asked Vikram if he would like to work on part-hours on Blazorise as he seamed good with Blazor stack. I also mentioned him a few times during the call that his project can only be used for his personal use, and not for commercial use since he based his project on Blazorise code base. And Blazorise has dual-based license that prohibits this. To which he agreed, and he agreed to mention Blazorise in credits of BlazorBootstrap. 
- Few days after the call he declined my offer to work with us. We went our separate ways from there. But not before I asked him once again to mention Blazorise in credits.
- Fast forward one month and seeing that he still didn’t acknowledge my request, I opened a PR that mentions Blazorise in credits(https://github.com/vikramlearning/blazorbootstrap/pull/329). He closed it that same day saying he will do it himself later. And everything stayed at that.

---

Fast forward to Feb 12th 2024, I sent him an official email asking once again to respond to my previous requests and to do the following. 

- mention in the CREDITS that BlazorBootstrap core code-base is based upon the code-base from Blazorise,
- make absolute sure that none of BlazorBootstrap users or consumers are a commercial entity as that might complicate stuff for everyone involved

Vikram responded on Feb 14th to an email saying he will let us know more on Feb, 16th.

During that time I noticed that he started renaming some parts of the code: https://github.com/vikramlearning/blazorbootstrap/pull/556/commits/b60d4b4e5386ab49d460d36963c1063ac15eb451
I asked him to stop doing so until we discuss it further. No response after that.

Today, on Feb 16th, in his email, which was ChatGPT generated, he said that he will remove those parts from the code base. But he just renamed them.

Now, I don’t know what motives Vikram has. Why he can’t write a single line in his credits to mention Blazorise. I can only see that he is not being honest with us at Blazorise. Nor he was honest with the people that trust his work and use his project. I don’t know what his plans are for the future of this project. I only ask him to acknowledge the work that he took and the work of all the people that contributed to Blazorise.

**Comment by gvreddy579** [comment]
Dear Mladen,

I acknowledge your frustration and disappointment, and these emotions are certainly understandable. However, public attacks, personal shaming, and the use of unprofessional language towards any individual are considered "unacceptable behavior" and violate our Code of Conduct (https://www.contributor-covenant.org/version/2/1/code_of_conduct/). This is a reminder that such conduct is not tolerated within our community.

Instead of focusing on negative emotions and accusations, let's strive to address the ongoing concerns regarding BlazorBootstrap productively and respectfully in the official email chain where discussions are already taking place.

Coming back to the CREDITS page mentions, We appreciate you raising this issue again. As previously mentioned, we acknowledge the importance of proper credits and are committed to addressing it. We already have an open issue(https://github.com/vikramlearning/blazorbootstrap/issues/330) which hasn't been resolved yet.

As an open-source project, we rely on the contributions and patience of our community. While we strive to respond promptly, Open-source projects rely on volunteers with diverse commitments. We appreciate your understanding as we balance these commitments with project needs. We assure you that the open issue regarding credits is still on our radar and will be addressed soon.

We appreciate your understanding of the open-source development process and the time it can take to address every concern. Your continued patience and participation are valuable to the project's growth

However, I see that a similar issue already exists in the backlog (https://github.com/vikramlearning/blazorbootstrap/issues/330). To avoid duplicating efforts, I will close this issue.

If you have any further questions or concerns, please do not hesitate to contact us.

**Comment by gvreddy579** [comment]
Taken care of credits in https://github.com/vikramlearning/blazorbootstrap/pull/576
