### ISSUE TITLE
Dropdown SubMenu

### ISSUE THREAD

**Issue by mrcorale** [vikramlearning/blazorbootstrap#633]
"We've identified an issue: a dropdown submenu is missing in the section. Is it possible to add another menu item as per the given image?"
![bootstrap-dropdown-menu](https://github.com/vikramlearning/blazorbootstrap/assets/52911474/f6f62ec6-5ec4-4da2-aa98-6548b6c9c9a6)

**Comment by gvreddy04** [comment]
@mrcorale Thank you for using Blazor Bootstrap. Bootstrap's Dropdown component currently does not support multiple levels. If this functionality becomes a more popular request, we will consider creating a new component instead of breaking the behavior of the existing Dropdown component. Therefore, it is not planned for implementation at this moment.

Link: https://getbootstrap.com/docs/5.3/components/dropdowns/
